# Generated by Django 4.2.7 on 2023-11-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_time_request",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
